#!/bin/bash
#
# XRPL Validator Dashboard - Repository Cleanup Script
# Removes development artifacts before pushing to GitHub
#

set -e

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

PROJECT_DIR="/home/grapedrop/projects/xrpl-validator-dashboard"

echo -e "${BLUE}================================================================================================${NC}"
echo -e "${BLUE}XRPL Validator Dashboard - Repository Cleanup${NC}"
echo -e "${BLUE}================================================================================================${NC}"
echo ""
echo -e "${YELLOW}This script will remove development artifacts and obsolete files before GitHub push.${NC}"
echo ""

# Files to remove
FILES_TO_REMOVE=(
    "ALERTS.md"
    "INSTALLATION_TRACKING.md"
    "SETUP.md"
    "restart_xrpl-monitor.sh"
    "list_metrics.sh"
    "package-python-source.sh"
    "query_validator.py"
)

# Show what will be removed
echo -e "${BLUE}Files that will be removed:${NC}"
echo ""
for file in "${FILES_TO_REMOVE[@]}"; do
    if [ -f "${PROJECT_DIR}/${file}" ]; then
        echo -e "  ${RED}✗${NC} ${file}"
    else
        echo -e "  ${YELLOW}⊘${NC} ${file} ${YELLOW}(already removed)${NC}"
    fi
done
echo ""

# Files to keep
echo -e "${BLUE}Files that will be KEPT (essential for new setup):${NC}"
echo ""
echo -e "  ${GREEN}✓${NC} setup.py (new wizard)"
echo -e "  ${GREEN}✓${NC} cleanup.sh (service cleanup)"
echo -e "  ${GREEN}✓${NC} install-service.sh (systemd installer)"
echo -e "  ${GREEN}✓${NC} docker-compose.yml"
echo -e "  ${GREEN}✓${NC} requirements.txt"
echo -e "  ${GREEN}✓${NC} README.md (updated)"
echo -e "  ${GREEN}✓${NC} HOW_IT_WORKS.md (updated)"
echo -e "  ${GREEN}✓${NC} GRAFANA_DASHBOARD.md"
echo -e "  ${GREEN}✓${NC} LICENSE (or LICENSE.md)"
echo -e "  ${GREEN}✓${NC} .gitignore"
echo -e "  ${GREEN}✓${NC} src/ (entire Python source)"
echo -e "  ${GREEN}✓${NC} compose/ (Prometheus & Grafana configs)"
echo -e "  ${GREEN}✓${NC} dashboards/ (dashboard templates)"
echo -e "  ${GREEN}✓${NC} images/ (screenshots)"
echo ""

# Confirm
echo -e "${YELLOW}This will permanently delete the files listed above.${NC}"
read -p "Continue with cleanup? [y/N]: " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}Cleanup cancelled.${NC}"
    exit 0
fi

echo ""
echo -e "${BLUE}Step 1: Removing obsolete files...${NC}"

removed_count=0
for file in "${FILES_TO_REMOVE[@]}"; do
    if [ -f "${PROJECT_DIR}/${file}" ]; then
        rm -f "${PROJECT_DIR}/${file}"
        echo -e "${GREEN}  ✓ Removed: ${file}${NC}"
        ((removed_count++))
    fi
done

if [ $removed_count -eq 0 ]; then
    echo -e "${GREEN}  ✓ No files to remove (already clean)${NC}"
else
    echo -e "${GREEN}  ✓ Removed ${removed_count} file(s)${NC}"
fi
echo ""

# Remove empty directories (if any)
echo -e "${BLUE}Step 2: Checking for empty directories...${NC}"
if [ -d "${PROJECT_DIR}/.project" ] && [ -z "$(ls -A ${PROJECT_DIR}/.project)" ]; then
    rmdir "${PROJECT_DIR}/.project"
    echo -e "${GREEN}  ✓ Removed empty .project directory${NC}"
else
    echo -e "${GREEN}  ✓ No empty directories to remove${NC}"
fi
echo ""

# Clean up Python cache
echo -e "${BLUE}Step 3: Cleaning Python cache files...${NC}"
cd "${PROJECT_DIR}"
find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
find . -type f -name "*.pyc" -delete 2>/dev/null || true
find . -type f -name "*.pyo" -delete 2>/dev/null || true
echo -e "${GREEN}  ✓ Python cache cleaned${NC}"
echo ""

# Clean up generated files (but keep data/ and logs/ structure)
echo -e "${BLUE}Step 4: Cleaning generated runtime files...${NC}"
if [ -f "${PROJECT_DIR}/config.yaml" ]; then
    echo -e "${YELLOW}  ⚠ config.yaml exists (generated by setup.py)${NC}"
    read -p "    Remove config.yaml? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -f "${PROJECT_DIR}/config.yaml"
        echo -e "${GREEN}  ✓ Removed config.yaml${NC}"
    else
        echo -e "${YELLOW}  ⊘ Kept config.yaml${NC}"
    fi
fi

if [ -d "${PROJECT_DIR}/data" ] && [ "$(ls -A ${PROJECT_DIR}/data 2>/dev/null)" ]; then
    echo -e "${YELLOW}  ⚠ data/ directory contains files${NC}"
    read -p "    Remove data/*.db files? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -f "${PROJECT_DIR}/data"/*.db "${PROJECT_DIR}/data"/*.db-* 2>/dev/null || true
        echo -e "${GREEN}  ✓ Removed database files${NC}"
    else
        echo -e "${YELLOW}  ⊘ Kept database files${NC}"
    fi
fi

if [ -d "${PROJECT_DIR}/logs" ] && [ "$(ls -A ${PROJECT_DIR}/logs 2>/dev/null)" ]; then
    echo -e "${YELLOW}  ⚠ logs/ directory contains files${NC}"
    read -p "    Remove logs/*.log files? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -f "${PROJECT_DIR}/logs"/*.log 2>/dev/null || true
        echo -e "${GREEN}  ✓ Removed log files${NC}"
    else
        echo -e "${YELLOW}  ⊘ Kept log files${NC}"
    fi
fi
echo ""

# Summary
echo -e "${GREEN}================================================================================================${NC}"
echo -e "${GREEN}Repository Cleanup Complete!${NC}"
echo -e "${GREEN}================================================================================================${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo -e "  1. Review changes:"
echo -e "     ${YELLOW}git status${NC}"
echo ""
echo -e "  2. Add all changes:"
echo -e "     ${YELLOW}git add -A${NC}"
echo ""
echo -e "  3. Commit with proper attribution:"
echo -e "     ${YELLOW}git config user.name 'realgrapedrop'${NC}"
echo -e "     ${YELLOW}git config user.email 'captain@grapedrop.xyz'${NC}"
echo -e "     ${YELLOW}git commit -m 'Refactor to wizard-based setup with auto-configuration'${NC}"
echo ""
echo -e "  4. Push to GitHub:"
echo -e "     ${YELLOW}git push origin main${NC}"
echo ""
echo -e "${GREEN}Repository is ready for push!${NC}"
echo ""
